spring:
  application:
    name: provider-plan-service

mybatis:
  type-aliases-package: cn.ann.financial.manager.provider.user.domain
  mapperLocations: classpath:mapper/*.xml

dubbo:
  scan:
    base-packages: cn.ann.financial.manager.provider.plan.service